version: '3.8'

services:
  libreoffice-converter:
    build:
      context: .
      dockerfile: Dockerfile.libreoffice
    container_name: libreoffice-converter
    ports:
      - "8080:8080"
    volumes:
      - ./public/uploads:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3