version: '3.8'

services:
  libreoffice:
    image: libreoffice/online:latest
    container_name: libreoffice-converter
    ports:
      - "3001:9980"
    environment:
      - domain=localhost
      - username=admin
      - password=admin
      - extra_params=--o:ssl.enable=false --o:net.proto=IPv4
    volumes:
      - ./public/uploads:/data
    networks:
      - libreoffice-net
    restart: unless-stopped

networks:
  libreoffice-net:
    driver: bridge